### ISSUE TITLE
عدم اجرای بازی و کرش کردن قبل از نمایش ارم یونیتی

### ISSUE THREAD

**Issue by virtouso** [sibche/SibcheStoreKit-Unity#1]
سلام. وقتتون بخیر
من داشتم پلاگینتون رو روی یونیتی 5.6.7 تست میکردم.  همون اول کار که اصلا ارم یونیتی هم بالا نیومده پیام :
کرش میده که 
thread1: signal sigbrt
dyId: Library not loaded: @sibcheStoreKit reference from.... 
reason: image not found

توی آموزش گیت زدید که حداقل یونیتی 2019. میخواستم بدونم دلیلش قطعا این هست؟ چون نباید فیچری باشه که به ورژن یونیتی وابسته باشه.

**Comment by virtouso** [comment]
باید کتابخونه سبیچه تو امبدد اضافه میشد. الان به نظر میرسه همه فیچرها دارن کار میکنن. پلاگین روی یونیتی 5 هم کار میکنه

**Comment by mehdihz** [comment]
> سلام. وقتتون بخیر
> من داشتم پلاگینتون رو روی یونیتی 5.6.7 تست میکردم. همون اول کار که اصلا ارم یونیتی هم بالا نیومده پیام :
> کرش میده که
> thread1: signal sigbrt
> dyId: Library not loaded: @sibcheStoreKit reference from....
> reason: image not found

We already described in documentation to embed SibcheStoreKit.framework as a `embedded resource` into your project [here](https://docs.sibche.com/?csharp#767f8214f1).

It's enough to let the bellow code to be active into the `SibcheBuildPostProcessor.cs` file:

`
AddSibcheFrameworkAsEmbed(path);
`

Within this code, we add our framework as embedded resource to your unity project.

> توی آموزش گیت زدید که حداقل یونیتی 2019. میخواستم بدونم دلیلش قطعا این هست؟ چون نباید فیچری باشه که به ورژن یونیتی وابسته باشه.
> باید کتابخونه سبیچه تو امبدد اضافه میشد. الان به نظر میرسه همه فیچرها دارن کار میکنن. پلاگین روی یونیتی 5 هم کار میکنه

This is because we tested with the latest Unity version and not sure if work with lower versions.
Thanks to your guidance. I'll change required version to 5 in documentation 👍

**Comment by mehdihz** [comment]
I'm closing the issue as it's not technical issue
